/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-container': 'var(--surface-container)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-bright': 'var(--surface-bright)',
        'surface-variant': 'var(--surface-variant)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'outline-variant': 'var(--outline-variant)',
        'on-primary': 'var(--on-primary)',
        primary: {
          DEFAULT: 'rgba(var(--primary), <alpha-value>)',
          container: 'rgba(var(--primary-container), <alpha-value>)',
          glow: 'rgba(76, 215, 246, 0.5)',
        },
        secondary: {
          DEFAULT: 'rgba(var(--secondary), <alpha-value>)',
          container: 'rgba(var(--secondary-container), <alpha-value>)',
          glow: 'rgba(221, 184, 255, 0.5)',
        },
        tertiary: {
          DEFAULT: 'rgba(var(--tertiary), <alpha-value>)',
          container: 'rgba(var(--tertiary-container), <alpha-value>)',
        },
        cyan: {
          50: 'rgba(var(--cyan-50), <alpha-value>)',
          100: 'rgba(var(--cyan-100), <alpha-value>)',
          200: 'rgba(var(--cyan-200), <alpha-value>)',
          300: 'rgba(var(--cyan-300), <alpha-value>)',
          400: 'rgba(var(--cyan-400), <alpha-value>)',
          500: 'rgba(var(--cyan-500), <alpha-value>)',
          600: 'rgba(var(--cyan-600), <alpha-value>)',
          700: 'rgba(var(--cyan-700), <alpha-value>)',
          800: 'rgba(var(--cyan-800), <alpha-value>)',
          900: 'rgba(var(--cyan-900), <alpha-value>)',
          950: 'rgba(var(--cyan-950), <alpha-value>)',
        },
        blue: {
          50: 'rgba(var(--blue-50), <alpha-value>)',
          100: 'rgba(var(--blue-100), <alpha-value>)',
          200: 'rgba(var(--blue-200), <alpha-value>)',
          300: 'rgba(var(--blue-300), <alpha-value>)',
          400: 'rgba(var(--blue-400), <alpha-value>)',
          500: 'rgba(var(--blue-500), <alpha-value>)',
          600: 'rgba(var(--blue-600), <alpha-value>)',
          700: 'rgba(var(--blue-700), <alpha-value>)',
          800: 'rgba(var(--blue-800), <alpha-value>)',
          900: 'rgba(var(--blue-900), <alpha-value>)',
          950: 'rgba(var(--blue-950), <alpha-value>)',
        },
        error: {
          DEFAULT: '#ffb4ab',
        },
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Outfit', 'sans-serif'],
        body: ['Outfit', 'sans-serif'],
        code: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
